@url_dev=http://localhost:8080/v1/api
###signup
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 021ee34a3780763e754c19b0dcfa721baec7b684848ad7a7db1cfdd37f92935599445c6c1c2f99f34cfa04fec4536d90c9534c4ac9d07856a8dc41b875a204c0

{
    "name":"Shop Tips",
    "email":"shoptipjs211552227@gmail.com",
    "password":"123"
}

###signin
POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key: 021ee34a3780763e754c19b0dcfa721baec7b684848ad7a7db1cfdd37f92935599445c6c1c2f99f34cfa04fec4536d90c9534c4ac9d07856a8dc41b875a204c0

{
    "name":"Shop Tips",
    "email":"shoptipjs21155227@gmail.com",
    "password":"123"
}

# {
#   "key": "-----BEGIN RSA PUBLIC KEY-----\nMIICCgKCAgEA0LB5RK5niBtZ6etC7EUt4xDa8YjHG/aOyFF6W8WUkAtqVdxkuKPj\nZD0eIl3xsUsvQ3iNZSvzDOD+/Y9fu2UcpkeUA86YEBVl2YSw/qLPwL2TLieih2TO\ntGdRtuopZXjLjm4obCvqpDgRmU4SAc21nsrg3Y4K0wG2kE6ApX0lYsjPhcEnY3+R\nhHtc7zNf0Hb34Bp3mdc4AGWKf4adKlhBtb2531+h6znoxF4B++zQ2A+zhcsEYIq/\ndWaODpV4c5Q4rKNQReQFtZW+0wEH5LmBHSl/17NjSFLYXWP8lJJ+qks7kUMn3rz9\ngXl3irxPlTI/l+kxkDZwntZFmoTvUZdVvVYjxODjEvIU2UwD8U2AyKNX5eHk6vrb\nGQ/cQdlaELmpDjufHEt+dxGnr/+8S5Q8T6JPCiVLfDsL4xn9XzSaVyQEPqjoJ5ak\nYAsuZupDH6HBA6TjGT80E2wzULpGZJGRVY8I5jDm9VgrVre/NGpBaD7qTpGdQGml\nUuU6yHq8FN2oYoTFRpfzJgmbpFZEsJd3Q7fbidm13p6bQ9dBzp6+Q1aCBeJtrZM7\ns+8UKD1ggMrdwOdsvNGWQttvfKdmc87juV8TEq3253vvcZfHhAjf03Fke8/43nsd\nr/QsQHSjnHgrSzwIVFHqr8SLo61ucGXgVLJ6khpqFJ8pi/zrtTVEvg8CAwEAAQ==\n-----END RSA PUBLIC KEY-----",

#     "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njk1MzJlOTVjYmJlZmI1MmM2ODBkOGEiLCJlbWFpbCI6InNob3B0aXBqczIxMTU1MjIyN0BnbWFpbC5jb20iLCJpYXQiOjE3MjExMjAxNTksImV4cCI6MTcyMTcyNDk1OX0.wC6SGjVwazgaO7OQ5EC8py10LV_FuM2G7a55I05-mHDyIZTxEeSLw0EG_M4LIBwEuo5efkRTYS7IfzCFDKCwk-taSg-ccF2yaAqUYAuFI2WoRvWPnksgv04pMxTv6gvZW7OJGBwvy1RtNfsCGz35xbqxZKdCW3CFnE99NK9U1jiTn14Y6cc7GRJXMB1Y84YRiHuj9rI0DbwgRRRk9-Z0Vsfnz5fAqXdJcVblbVsTpzPCmymnuVzbywigSFajLyzellSU-B0w3RYuaCAJJepMb8zaAFLbm065oMeNqtoXoB8rMLYlGDqW7Wa_yy8KJFhOIzmTmd-cRwFGTofyJObJuyGIvgJSjYe8RSew8zIG326aGubGynecvEeqLioXVu9IoPsTL6KrPm9MM_caUD6BTxJGvsU-KE9czbWXVHK8g3OopdN4PDQtg35caG-9PCf3iY7ecfD9EYrsqwSQrCBx-V_Pj7iKTWMg8JwO260kCaIfVuccJSY_FTHFXenIXtKyvO2WMNh-1eX1kYf0vHShGIS2Ca_LwNQo42kp7Zn7Ey50Wz9CEUrTEAmuuXuuwhXj-6wJ7oKiPPDJYr83s2wwHgjZv_hh9nKL9NE9utmm4uiKlRkzFuPxrfHvcd-gyNeq-55gMNd7Bb7io5ousOcUpSmxdoMD9ksEejE78JC2z5U"
# }

###logout
POST {{url_dev}}/shop/logout
Content-Type: application/json
x-api-key: 021ee34a3780763e754c19b0dcfa721baec7b684848ad7a7db1cfdd37f92935599445c6c1c2f99f34cfa04fec4536d90c9534c4ac9d07856a8dc41b875a204c0
x-client-id: 669532e95cbbefb52c680d8a
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njk1MzJlOTVjYmJlZmI1MmM2ODBkOGEiLCJlbWFpbCI6InNob3B0aXBqczIxMTU1MjIyN0BnbWFpbC5jb20iLCJpYXQiOjE3MjEwNTg1MTAsImV4cCI6MTcyMTIzMTMxMH0.JlGj6AcPzpszpMOUoesAwWCuJSo3nyHCmDJi3vbhy6iCKB7LecbqjX_vzs3M2CaZSEu055Tn7SEr8kkiiMcmiYcC9B_2ld9ik4FKwxG11iDrimEMniOV7pDtllO3ZZ7otKvkWDTU6qhkYxNXsBEMyKYNLe28Zaw7rGZS9Pd5DSL_pFHLIZzIBK4i7Kkz-k6Lxfgw65kZkJvCldWf7lQGLToCYXLcFhxISvjpHwkFqiNsyVnuDryPJeDiGQ0GkS5lMQ2Uq5wM1kc8khbN4nJclehg8RrnkpqV_GoBpSTpDhLheqRwMUs5t81g2XosWJS51JlpSyaf4wf6GTcDagpwhp3mE1n9ReiCfiN4Ie9eEwBTjSSFiBdt6pYWcNXwQd9bgc2okdhRqOlouublu003MAi-ykr8mdqMXGw2HjpxW0VxrOL58WyvDbkq72DRw38Pu9rYd2AbdyNXB5p4HTNN6CasUqPwJ4BmfdSYG72HJdHWIbYjJzD3tjLREGraEmuO6gCK9QqWCECFH51PfgtyhwZKNJTGBcEZu_AsuGgO5GnipDUVYkDUl45nI4jLQW-rsQaSJRBYEzQN61CwYek3U1dxBgz4rJ3bXMCnuzrfZVddkM2otcC57c0tiCV3E-rkFryWawD_yP2u_DpvZcIOdV06BouPORAvvVVy5SfJM0M


###handlerRefreshToken
POST {{url_dev}}/shop/handlerRefreshToken
Content-Type: application/json
x-api-key: 021ee34a3780763e754c19b0dcfa721baec7b684848ad7a7db1cfdd37f92935599445c6c1c2f99f34cfa04fec4536d90c9534c4ac9d07856a8dc41b875a204c0
x-client-id: 6695321d5d8a7a6cddde90d4
x-rtoken-id: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njk1MzIxZDVkOGE3YTZjZGRkZTkwZDQiLCJlbWFpbCI6InNob3B0aXBqczIxMTU1MjI3QGdtYWlsLmNvbSIsImlhdCI6MTcyMTE0MjA2MSwiZXhwIjoxNzIxNzQ2ODYxfQ.VvWVOxsS9vVmqYc0XoiqHhMKoR74HZsQYY76F8ulsXn-OciPoQj8BawiX6F_HDcDhmWEavi8NgZWwAMP6OfCAOd-tqCUN1h0g-cYhtQv_LNeh3WjjuweUDMPwMEQhFEHh5TMtp7MJkQSfsx0zPmoIeFaDuMNmIWW3xTQdomBgBSXF4NWivANv4D2mG4ytgCDrZiPqAPlRUjh9i8YonYj-4pLtGO22AX6MrLaQAM629xvHde2Nk8QGFVPb4fdx_6ZWrwGHHlt_-6oQE0A6LBY0zAtCTgT_SzrJhkjt9ErxIo9I94me0kUEuzpFpSxfNbPrmx5gh0t5Rpn5ozAdNscHBrNAqfqTsbOL95zkgMiqNTisb7RRcLuzp6x0obAQlTw_c6QScBHZ0wkZROEF-z_I_k6pxAmXZFf-mirY39K3Cud6cpJ6OZHYE_h0Io-PMQfrA6KZptIgZvUh1W0OqmUu6GxF8ieJkFy6B65vgQe2lSzVs41tZBll1rWJ1XMYorzxwY6AMfcfefE0i9oziX4K48PRvBVVKeXDlwnaTkFmA4K4N_Qx6rISiJ_8OK9kF1CpYyf5BOHrYay9oPr7heeXkMzmX-L5HotYmpIl7Fz_oo77eYr9-gEm9QiRCxwRLCLVbty497U2uR5Y3FhMsRZGj6RQngngInpEP7mYDVhzkw
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njk1MzJlOTVjYmJlZmI1MmM2ODBkOGEiLCJlbWFpbCI6InNob3B0aXBqczIxMTU1MjIyN0BnbWFpbC5jb20iLCJpYXQiOjE3MjExMjQyODUsImV4cCI6MTcyMTI5NzA4NX0.q-bdFNa_9yEcEWFyn9ld50NkBfcjl5bnafoCD2REmk23-oInPqyUh7_my0NQ3H5sIvL_U03OzKBXNBmeuUoFDPekly8ZkSm9lB4SefgXgQk0VxCAR7xe7RryT-EHiKIo-b7Bkxcpjs6crLakb0rKajQl72LRA_wKOK5YKVsTKq7Ep2tgGeWQuU4Ocey6VbNTLlrE1EaH3YNfCDcYhkwu1kThCrlj7hDrQsh64bd_j2EjG2hmcd3AqqajUGZtR_rP3ZSkeo45kvqZDwpIybLz-9WCjlyi-Bv9BWbLP7Ny1ZrO_gtW2jPnaZVsiCzdCv57fHaY4c1NAy1NZCezWx__p0XXsY_gndMbsxTcdLvjdhwp2wmzYo8E3R_UPxivnEst-dZu_jthUJCHvFi6C3N5DBEPy7O5aFMacZR4IUq6u1Ek_ouhdhcXdSNOKOVWZ_ON2LLHkd4MUZPnemsPuzHBw3s1bHZhXujC4gnMOvO-myyugL4BgznZlXqH_UWlr8mQsX6o-x4iivPpRu955NsrWqkjpb-DoThXE5pRG_Y9UrdPvT_qd2ssd8UUxqK0GwsGOWpjDDOoH7euDJO6hKGEcnOxHr287ZoeWUoNo5Q2jFRD5KNkFr-p-bfnoyomn5IKWi2H34NPF2Lur-MexjWJfF2UTkJRWpw01L3CR-GpEKc
 
