@url_dev=http://localhost:8080/v1/api

### create new discount code
POST {{url_dev}}/discount
Content-Type: application/json
x-api-key: 021ee34a3780763e754c19b0dcfa721baec7b684848ad7a7db1cfdd37f92935599445c6c1c2f99f34cfa04fec4536d90c9534c4ac9d07856a8dc41b875a204c0
x-client-id: 6695321d5d8a7a6cddde90d4
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njk1MzIxZDVkOGE3YTZjZGRkZTkwZDQiLCJlbWFpbCI6InNob3B0aXBqczIxMTU1MjI3QGdtYWlsLmNvbSIsImlhdCI6MTcyMTYzODI5MSwiZXhwIjoxNzIxODExMDkxfQ.ckDxw5feRmh-I0MDuc-EkAf040P18TZpjH1IGWvqxvd_9p_NEY5snEecpmyeAyWcGx0On4ikMvHvLZrrhp4W02-cPf4AbA6WwCQUlAVaneosmaDUxwenH5eUaAZGyO0D9GD2AIdFSLMfRlx54x5dv9g6bYa76tzaS-FhqoZm-XOniUJ5z02FzJ-fFtP8u8bLiaBTdYbdC1lranegxlkfLmY0VVw5ckeXEszlJ73RYvVAFQ0mPMLf6Rz4vJ3xoZHtp3EuB19v5Pe32CamMS2R4bxr51xQf95LgXKFJDaaZEedfGbfvQXXrCcHY2mLzjatSn2fMBUw11tU4nFHc-0Lq1ZTMVRoWKjGNQS8gupov8vl9RC-3Z8y41gEapUF8OmtcweS1ZdcYqOZqLqhcof_3t1Y0k1k7II6QjhASPZvwS6LiAqyS5SLbkPweXQp_3g-0s1lUwBXt0kkD5mbM_JpzpMF9KI02g9wQ5vtoWHnbP4vxQ_4Y4g-oYVbCoom7TWNZHt3B2xk74Dd-dSCnVW_Qizd4q4EuXRrZN47WQBWOQAg7XtHhBQpd574h8CMtvxdOhW7DNw_EF15kkHgoohXCQpzC0lzPrqNlYwYCCazpm1TkVPeDUSedF14Dl1so4uhE0jE87HB60YV1y00EItj-VeFgvwhkViCT22-8tq0IYw

{
    "name": "name fixed amount",
    "description":"description",
    "type": "fixed_amount",
    "value":20000,
    "max_value":30000,
    "code":"SHOP-fix-11112",
    "start_date":"2024-04-25 09:00:00",
    "end_date":"2025-04-28 09:00:00",
    "max_uses":100,
    "uses_count":0,
    "users_used":[],
    "max_uses_per_user":1,
    "min_order_value":200000,
    "create_by":{},
    "is_active":true,
    "applies_to":"specific",
    "product_ids":["6699d8cd1f13e195a1a56028","669a22e2708fda5472ba0225"]

}

### get products that can use this code
GET {{url_dev}}/discount/list_product_code?code=SHOP-percentttt-1111
Content-Type: application/json
x-api-key: 021ee34a3780763e754c19b0dcfa721baec7b684848ad7a7db1cfdd37f92935599445c6c1c2f99f34cfa04fec4536d90c9534c4ac9d07856a8dc41b875a204c0
x-client-id: 6695321d5d8a7a6cddde90d4
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njk1MzIxZDVkOGE3YTZjZGRkZTkwZDQiLCJlbWFpbCI6InNob3B0aXBqczIxMTU1MjI3QGdtYWlsLmNvbSIsImlhdCI6MTcyMTYzODI5MSwiZXhwIjoxNzIxODExMDkxfQ.ckDxw5feRmh-I0MDuc-EkAf040P18TZpjH1IGWvqxvd_9p_NEY5snEecpmyeAyWcGx0On4ikMvHvLZrrhp4W02-cPf4AbA6WwCQUlAVaneosmaDUxwenH5eUaAZGyO0D9GD2AIdFSLMfRlx54x5dv9g6bYa76tzaS-FhqoZm-XOniUJ5z02FzJ-fFtP8u8bLiaBTdYbdC1lranegxlkfLmY0VVw5ckeXEszlJ73RYvVAFQ0mPMLf6Rz4vJ3xoZHtp3EuB19v5Pe32CamMS2R4bxr51xQf95LgXKFJDaaZEedfGbfvQXXrCcHY2mLzjatSn2fMBUw11tU4nFHc-0Lq1ZTMVRoWKjGNQS8gupov8vl9RC-3Z8y41gEapUF8OmtcweS1ZdcYqOZqLqhcof_3t1Y0k1k7II6QjhASPZvwS6LiAqyS5SLbkPweXQp_3g-0s1lUwBXt0kkD5mbM_JpzpMF9KI02g9wQ5vtoWHnbP4vxQ_4Y4g-oYVbCoom7TWNZHt3B2xk74Dd-dSCnVW_Qizd4q4EuXRrZN47WQBWOQAg7XtHhBQpd574h8CMtvxdOhW7DNw_EF15kkHgoohXCQpzC0lzPrqNlYwYCCazpm1TkVPeDUSedF14Dl1so4uhE0jE87HB60YV1y00EItj-VeFgvwhkViCT22-8tq0IYw


### get all the codes this shop has
GET {{url_dev}}/discount?shop=6695321d5d8a7a6cddde90d4
Content-Type: application/json
x-api-key: 021ee34a3780763e754c19b0dcfa721baec7b684848ad7a7db1cfdd37f92935599445c6c1c2f99f34cfa04fec4536d90c9534c4ac9d07856a8dc41b875a204c0
x-client-id: 6695321d5d8a7a6cddde90d4
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njk1MzIxZDVkOGE3YTZjZGRkZTkwZDQiLCJlbWFpbCI6InNob3B0aXBqczIxMTU1MjI3QGdtYWlsLmNvbSIsImlhdCI6MTcyMTYzODI5MSwiZXhwIjoxNzIxODExMDkxfQ.ckDxw5feRmh-I0MDuc-EkAf040P18TZpjH1IGWvqxvd_9p_NEY5snEecpmyeAyWcGx0On4ikMvHvLZrrhp4W02-cPf4AbA6WwCQUlAVaneosmaDUxwenH5eUaAZGyO0D9GD2AIdFSLMfRlx54x5dv9g6bYa76tzaS-FhqoZm-XOniUJ5z02FzJ-fFtP8u8bLiaBTdYbdC1lranegxlkfLmY0VVw5ckeXEszlJ73RYvVAFQ0mPMLf6Rz4vJ3xoZHtp3EuB19v5Pe32CamMS2R4bxr51xQf95LgXKFJDaaZEedfGbfvQXXrCcHY2mLzjatSn2fMBUw11tU4nFHc-0Lq1ZTMVRoWKjGNQS8gupov8vl9RC-3Z8y41gEapUF8OmtcweS1ZdcYqOZqLqhcof_3t1Y0k1k7II6QjhASPZvwS6LiAqyS5SLbkPweXQp_3g-0s1lUwBXt0kkD5mbM_JpzpMF9KI02g9wQ5vtoWHnbP4vxQ_4Y4g-oYVbCoom7TWNZHt3B2xk74Dd-dSCnVW_Qizd4q4EuXRrZN47WQBWOQAg7XtHhBQpd574h8CMtvxdOhW7DNw_EF15kkHgoohXCQpzC0lzPrqNlYwYCCazpm1TkVPeDUSedF14Dl1so4uhE0jE87HB60YV1y00EItj-VeFgvwhkViCT22-8tq0IYw

### get all the codes this shop has
GET {{url_dev}}/discount/amount
Content-Type: application/json
x-api-key: 021ee34a3780763e754c19b0dcfa721baec7b684848ad7a7db1cfdd37f92935599445c6c1c2f99f34cfa04fec4536d90c9534c4ac9d07856a8dc41b875a204c0
x-client-id: 6695321d5d8a7a6cddde90d4
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njk1MzIxZDVkOGE3YTZjZGRkZTkwZDQiLCJlbWFpbCI6InNob3B0aXBqczIxMTU1MjI3QGdtYWlsLmNvbSIsImlhdCI6MTcyMTYzODI5MSwiZXhwIjoxNzIxODExMDkxfQ.ckDxw5feRmh-I0MDuc-EkAf040P18TZpjH1IGWvqxvd_9p_NEY5snEecpmyeAyWcGx0On4ikMvHvLZrrhp4W02-cPf4AbA6WwCQUlAVaneosmaDUxwenH5eUaAZGyO0D9GD2AIdFSLMfRlx54x5dv9g6bYa76tzaS-FhqoZm-XOniUJ5z02FzJ-fFtP8u8bLiaBTdYbdC1lranegxlkfLmY0VVw5ckeXEszlJ73RYvVAFQ0mPMLf6Rz4vJ3xoZHtp3EuB19v5Pe32CamMS2R4bxr51xQf95LgXKFJDaaZEedfGbfvQXXrCcHY2mLzjatSn2fMBUw11tU4nFHc-0Lq1ZTMVRoWKjGNQS8gupov8vl9RC-3Z8y41gEapUF8OmtcweS1ZdcYqOZqLqhcof_3t1Y0k1k7II6QjhASPZvwS6LiAqyS5SLbkPweXQp_3g-0s1lUwBXt0kkD5mbM_JpzpMF9KI02g9wQ5vtoWHnbP4vxQ_4Y4g-oYVbCoom7TWNZHt3B2xk74Dd-dSCnVW_Qizd4q4EuXRrZN47WQBWOQAg7XtHhBQpd574h8CMtvxdOhW7DNw_EF15kkHgoohXCQpzC0lzPrqNlYwYCCazpm1TkVPeDUSedF14Dl1so4uhE0jE87HB60YV1y00EItj-VeFgvwhkViCT22-8tq0IYw

{
    "codeId":"SHOP-fix-11112",
    "userId":2,
    "shopId":"6695321d5d8a7a6cddde90d4",
    "products":[{
        "productId":"6699d8cd1f13e195a1a56028",
        "quantity":5,
        "price":120000
    }]
}