@url_dev=http://localhost:8080/v1/api
@auth=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njk1MzIxZDVkOGE3YTZjZGRkZTkwZDQiLCJlbWFpbCI6InNob3B0aXBqczIxMTU1MjI3QGdtYWlsLmNvbSIsImlhdCI6MTcyMTcwMzYzNSwiZXhwIjoxNzIxODc2NDM1fQ.UmZcH78G5HJ6PsVL8dQ7hdBZTvU_ADzrovKI6nRCSffEP_wwcsr87tvySJumh2ybX8rmK7mc0zQiKJTRx3TYayugg_zFABb5j_NoVUgzt64M9eQoqLZZJNYHTULN2A4vbxfl8iUYlnOMlJpfIICbCdgwUBRK7LzztiOaejvYhUe6CyImZYx8soKhesnQKicr60RuCtrvH3Q9nG4hg022KKuGgXmj2UisE4X1ZP2j1s2S0KKw2bEB-ytVwrZz-VesdvjGnVsVz5N3vpWaoFijkt_6z4QwAm2nIbLm_8U16XEpjJ0faH0x8_yIk9LoUl1wg-ZIdRNw2WL1IOLPyP3nGSqtlEJV9WwN9MrVpK4qmXofTOIwmmASiRFpvEuPPVbyI28e-XoLc2MKZbEv82L1x-BGQWEKoMKlXOGv0JUFMbpcjca5LhjwZ0VNhDDCOX4liTo1e1TjQdJqMjUa2wbboDEMgDdUZsB9pTwlld6gqdYZO0Jnk0ySG4S94gLsn_o0yZLshiLmaUh82-bwat18qvTAOAoWDbm8AcEvzWiVwYurN05_vNUz4qN6HpKADZTifd_K3mPZj2dFMmMOC9IHXKygDfiJBmd0rZGoSUSw0pcf-kiwZ2KnbuTrB2Iz3JE4pjYMzwb2OraebfpM_BHLQylhA2nJT2xoRKGwwkbVjKU

### create new product
POST {{url_dev}}/products
Content-Type: application/json
x-api-key: 021ee34a3780763e754c19b0dcfa721baec7b684848ad7a7db1cfdd37f92935599445c6c1c2f99f34cfa04fec4536d90c9534c4ac9d07856a8dc41b875a204c0
x-client-id: 6695321d5d8a7a6cddde90d4
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njk1MzIxZDVkOGE3YTZjZGRkZTkwZDQiLCJlbWFpbCI6InNob3B0aXBqczIxMTU1MjI3QGdtYWlsLmNvbSIsImlhdCI6MTcyMjIxOTAxMSwiZXhwIjoxNzIyMzkxODExfQ.nrzT6azsr41JnFgcHIez1QOgTZDjfHLvFwvChWRqh3a9q1i4Vc9CbC9xFOBgx_gAQAyWe4_bipb1pXX8cHZnC31LCrabf5TYNqP7exxvgdNw-KLQgFQ1HhqLi2NIkYZ9toHSrILTrXyp3dELBYUuLQKGk4wH6ybQWwuMIKJ9uge5Vw_T4lEeZgQ9YRNF41dEMBLPOXB66iUFhQx-akUAn7D6Gjx0gMW2WeEk5vryiwCau5n9RMiRfHhUotSU3ODGzU-D6uAngvh6ENl0TYxE8VlOTKRsbKJ6TtgvMNxsOca7v6pgjsE3YJFZ91aamH3dDKHJoRnvDyp9LTi1AhotxlC0TzYd0UrXlolnXtGOk-4oSBlotBrRqvW9UgimqDBx5ZTmK9N6PwaadR3xqv8mCxRihsRGX99De72TcQaaOz4ok7-4ONXR3oAbDuiakkbxP2bnxhIZCdhjSeOnJuTY6nWt_hjncqPkfvWpXXZIj4Yj8NcSxwlsaN__7VpJD4IfZyT9nrPLRH_pmWWKfrztNk-Rl9LFPtgSMyJQkrk3b-_R6JHFDSqC18YhTXKzuysNs93F7L1Rs477Yx5EdZB3WScPUTehNnYCYtSIKThRwoDQ0T0jfUmdFVbhzgr-QPsfooan7HyNWtrfUNswsSFi3Z7YsLqWb8YcAOCgXqQM_MI

    # "product_name":"New Jeans",
    # "product_description": "high quality denim jeans",
    # "product_price": 50,
    # "product_type": "Clothing",
    # "product_thumb": "url.com",
    # "product_quantity" : 5,
    # "product_attributes": {
    #     "brand": "Levi s",
    #     "size": "L",
    #     "material": "Denim"
    # }

    # "product_name":"New Jeans",
    # "product_description": "high quality denim jeans",
    # "product_price": 50,
    # "product_type": "Clothing",
    # "product_thumb": "url.com",
    # "product_quantity" : 5,
    # "product_attributes": {
    #     "brand": "Levi s",
    #     "size": "L",
    #     "material": "Denim"
    # }
{
    "product_name":"Ban chai thongm inh",
    "product_description": "do dung hoc sinh",
    "product_price": 1000,
    "product_type": "Furniture",
    "product_thumb": "url.com",
    "product_quantity" : 10,
    "product_attributes": {
        "brand": "Kim Hanh",
        "size": "XXL",
        "material": "WOOD"
    }
}

### get all drafts
GET {{url_dev}}/products/drafts/all
Content-Type: application/json
x-api-key: 021ee34a3780763e754c19b0dcfa721baec7b684848ad7a7db1cfdd37f92935599445c6c1c2f99f34cfa04fec4536d90c9534c4ac9d07856a8dc41b875a204c0
x-client-id: 6695321d5d8a7a6cddde90d4
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njk1MzIxZDVkOGE3YTZjZGRkZTkwZDQiLCJlbWFpbCI6InNob3B0aXBqczIxMTU1MjI3QGdtYWlsLmNvbSIsImlhdCI6MTcyMTcwMzYzNSwiZXhwIjoxNzIxODc2NDM1fQ.UmZcH78G5HJ6PsVL8dQ7hdBZTvU_ADzrovKI6nRCSffEP_wwcsr87tvySJumh2ybX8rmK7mc0zQiKJTRx3TYayugg_zFABb5j_NoVUgzt64M9eQoqLZZJNYHTULN2A4vbxfl8iUYlnOMlJpfIICbCdgwUBRK7LzztiOaejvYhUe6CyImZYx8soKhesnQKicr60RuCtrvH3Q9nG4hg022KKuGgXmj2UisE4X1ZP2j1s2S0KKw2bEB-ytVwrZz-VesdvjGnVsVz5N3vpWaoFijkt_6z4QwAm2nIbLm_8U16XEpjJ0faH0x8_yIk9LoUl1wg-ZIdRNw2WL1IOLPyP3nGSqtlEJV9WwN9MrVpK4qmXofTOIwmmASiRFpvEuPPVbyI28e-XoLc2MKZbEv82L1x-BGQWEKoMKlXOGv0JUFMbpcjca5LhjwZ0VNhDDCOX4liTo1e1TjQdJqMjUa2wbboDEMgDdUZsB9pTwlld6gqdYZO0Jnk0ySG4S94gLsn_o0yZLshiLmaUh82-bwat18qvTAOAoWDbm8AcEvzWiVwYurN05_vNUz4qN6HpKADZTifd_K3mPZj2dFMmMOC9IHXKygDfiJBmd0rZGoSUSw0pcf-kiwZ2KnbuTrB2Iz3JE4pjYMzwb2OraebfpM_BHLQylhA2nJT2xoRKGwwkbVjKU


### get all published
GET {{url_dev}}/products/published/all
Content-Type: application/json
x-api-key: 021ee34a3780763e754c19b0dcfa721baec7b684848ad7a7db1cfdd37f92935599445c6c1c2f99f34cfa04fec4536d90c9534c4ac9d07856a8dc41b875a204c0
x-client-id: 6695321d5d8a7a6cddde90d4
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njk1MzIxZDVkOGE3YTZjZGRkZTkwZDQiLCJlbWFpbCI6InNob3B0aXBqczIxMTU1MjI3QGdtYWlsLmNvbSIsImlhdCI6MTcyMTcwMzYzNSwiZXhwIjoxNzIxODc2NDM1fQ.UmZcH78G5HJ6PsVL8dQ7hdBZTvU_ADzrovKI6nRCSffEP_wwcsr87tvySJumh2ybX8rmK7mc0zQiKJTRx3TYayugg_zFABb5j_NoVUgzt64M9eQoqLZZJNYHTULN2A4vbxfl8iUYlnOMlJpfIICbCdgwUBRK7LzztiOaejvYhUe6CyImZYx8soKhesnQKicr60RuCtrvH3Q9nG4hg022KKuGgXmj2UisE4X1ZP2j1s2S0KKw2bEB-ytVwrZz-VesdvjGnVsVz5N3vpWaoFijkt_6z4QwAm2nIbLm_8U16XEpjJ0faH0x8_yIk9LoUl1wg-ZIdRNw2WL1IOLPyP3nGSqtlEJV9WwN9MrVpK4qmXofTOIwmmASiRFpvEuPPVbyI28e-XoLc2MKZbEv82L1x-BGQWEKoMKlXOGv0JUFMbpcjca5LhjwZ0VNhDDCOX4liTo1e1TjQdJqMjUa2wbboDEMgDdUZsB9pTwlld6gqdYZO0Jnk0ySG4S94gLsn_o0yZLshiLmaUh82-bwat18qvTAOAoWDbm8AcEvzWiVwYurN05_vNUz4qN6HpKADZTifd_K3mPZj2dFMmMOC9IHXKygDfiJBmd0rZGoSUSw0pcf-kiwZ2KnbuTrB2Iz3JE4pjYMzwb2OraebfpM_BHLQylhA2nJT2xoRKGwwkbVjKU

### publish a product
POST {{url_dev}}/products/publish/669a40ed2b5d352783c9cc49
Content-Type: application/json
x-api-key: 021ee34a3780763e754c19b0dcfa721baec7b684848ad7a7db1cfdd37f92935599445c6c1c2f99f34cfa04fec4536d90c9534c4ac9d07856a8dc41b875a204c0
x-client-id: 6695321d5d8a7a6cddde90d4
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njk1MzIxZDVkOGE3YTZjZGRkZTkwZDQiLCJlbWFpbCI6InNob3B0aXBqczIxMTU1MjI3QGdtYWlsLmNvbSIsImlhdCI6MTcyMTcwMzYzNSwiZXhwIjoxNzIxODc2NDM1fQ.UmZcH78G5HJ6PsVL8dQ7hdBZTvU_ADzrovKI6nRCSffEP_wwcsr87tvySJumh2ybX8rmK7mc0zQiKJTRx3TYayugg_zFABb5j_NoVUgzt64M9eQoqLZZJNYHTULN2A4vbxfl8iUYlnOMlJpfIICbCdgwUBRK7LzztiOaejvYhUe6CyImZYx8soKhesnQKicr60RuCtrvH3Q9nG4hg022KKuGgXmj2UisE4X1ZP2j1s2S0KKw2bEB-ytVwrZz-VesdvjGnVsVz5N3vpWaoFijkt_6z4QwAm2nIbLm_8U16XEpjJ0faH0x8_yIk9LoUl1wg-ZIdRNw2WL1IOLPyP3nGSqtlEJV9WwN9MrVpK4qmXofTOIwmmASiRFpvEuPPVbyI28e-XoLc2MKZbEv82L1x-BGQWEKoMKlXOGv0JUFMbpcjca5LhjwZ0VNhDDCOX4liTo1e1TjQdJqMjUa2wbboDEMgDdUZsB9pTwlld6gqdYZO0Jnk0ySG4S94gLsn_o0yZLshiLmaUh82-bwat18qvTAOAoWDbm8AcEvzWiVwYurN05_vNUz4qN6HpKADZTifd_K3mPZj2dFMmMOC9IHXKygDfiJBmd0rZGoSUSw0pcf-kiwZ2KnbuTrB2Iz3JE4pjYMzwb2OraebfpM_BHLQylhA2nJT2xoRKGwwkbVjKU
### search a product
GET {{url_dev}}/products/search/hoc sinh
Content-Type: application/json
x-api-key: 021ee34a3780763e754c19b0dcfa721baec7b684848ad7a7db1cfdd37f92935599445c6c1c2f99f34cfa04fec4536d90c9534c4ac9d07856a8dc41b875a204c0
x-client-id: 6695321d5d8a7a6cddde90d4
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njk1MzIxZDVkOGE3YTZjZGRkZTkwZDQiLCJlbWFpbCI6InNob3B0aXBqczIxMTU1MjI3QGdtYWlsLmNvbSIsImlhdCI6MTcyMTIwMzQ1NywiZXhwIjoxNzIxMzc2MjU3fQ.iTCB9lrhiXkYQ15-xYvxVGo5YyVyccm-TKxL258wvC2KhCsS1wCsc11h9Nelt-vrq1EaESyFjwYpTRlxgkR-x4xDBg5chxzcO2G_cNKn9l3qmYODgSTJZwJqqpjYKsodlklc9nVTIRIxnsHwPwgWTph8I_lkTS8v7ixTk0rsfYu55XGebrfNx4cve9a1uCj_8yT9vNmnSJlRTqSdrc9I7_3tRZisN_2Y3cJKJ8E5zWL2LuI4nNONqzOCKedRzrvNb_Oh3uROJgykRFOAvF5ljHPjqXCaNvkrNqBZP2jRG8RoF5OWwHPyimgkntZzBdY2F-ZluusLwl2kb2CPvCd9KruSor4kV_r2MSH7GP0SP_Pd0xTXpbjVsGXvFKE2gRyFog95z-8m500qQJxtZX3RDFjCnjuesDxfXSCeWWTrKFeF3QdUAm4ig2Q15ZP3tVc1vgzAemM7k1YkH8WaKE2oF1BpFj2HYtz7EREAkTj_TycJ8Erl10gsZlnM9rvTKPA9uA4of7lrN_V8gOYGydg2yYRpd4GkVeYLOw1DvHPg3npHmhzDnPegIw2skuB1P1yrxO7tDFxd4-uXnwLD4DnTDCyPHqF-aq8I6wpYGwY454HNnkJ7pzzpeCONSkFrIjqWd6l1XcMjCYYC_AAQIthqd9cTAQIqnBhewA7Q7XOYWkY

### get all products with filter
GET {{url_dev}}/products/
Content-Type: application/json
x-api-key: 021ee34a3780763e754c19b0dcfa721baec7b684848ad7a7db1cfdd37f92935599445c6c1c2f99f34cfa04fec4536d90c9534c4ac9d07856a8dc41b875a204c0
x-client-id: 6695321d5d8a7a6cddde90d4
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njk1MzIxZDVkOGE3YTZjZGRkZTkwZDQiLCJlbWFpbCI6InNob3B0aXBqczIxMTU1MjI3QGdtYWlsLmNvbSIsImlhdCI6MTcyMTk3NzAwMSwiZXhwIjoxNzIyMTQ5ODAxfQ.Rf9ro3fm7wU-69ObfrKDnDmHIFSOrppwfwkWl6yBDyNgVGtbq69M2BvoGgWXSlZqlTUunt_fXL7GVknrDUE9_gTz6DIbtFQHU5dY_d7t5UR1wGnSOCE3GBC3Q9mCX1qHkttu9tur2g9culNcrqWgMtMEweKAsy3X-liLXr4A7XFG2tCLRrtESuUp1HdKsy4dqWt2aNZvJyuQrURkeC9h0OlXMXGgtkA_H9kZ4NkLQBA3wWH8BcXtHr_kHNBPgseEM4lcrLpjYhSahzFJvfKC34BJXkOmSRu1Gz3iCsKXDZuS_wPZHgSYmygyOZV8giEm-7ilp7-P5EG8HMmTCcfbsM0i2A6lFncZOY2kdtApugNJyUudyJHMgyZOaihwYeMcejEnRMYw_ghKzu0bgTiSmaAj4NT_qXwYEso9hZdlkwDpYIoOEYIW0RyQlOE2XV7GDMdVRfT3VTckPBumGRfQQ9T60i_Klf_aA2We6YYR1qW-pl9H0zHxpRdKm4uoofKJX-uHsDitF2DedMhpNcvLYeqibeifER1OLKBTbUHdZEf4Dhij0Jnq1mF10N0Ox9sGDlzGHiFGTzz989KKlym3rYoHeWJmbzvUW2W2URKIZmkL6egtVUmi014rjuBa5_-JDvXKFijm8KEIwI7iaxe3kAdpw5t0eV8nh1jzc2W4REc

### get a product 
GET {{url_dev}}/products/6699d8cd1f13e195a1a2560283
Content-Type: application/json
x-api-key: 021ee34a3780763e754c19b0dcfa721baec7b684848ad7a7db1cfdd37f92935599445c6c1c2f99f34cfa04fec4536d90c9534c4ac9d07856a8dc41b875a204c0
x-client-id: 6695321d5d8a7a6cddde90d4
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njk1MzIxZDVkOGE3YTZjZGRkZTkwZDQiLCJlbWFpbCI6InNob3B0aXBqczIxMTU1MjI3QGdtYWlsLmNvbSIsImlhdCI6MTcyMTIwMzQ1NywiZXhwIjoxNzIxMzc2MjU3fQ.iTCB9lrhiXkYQ15-xYvxVGo5YyVyccm-TKxL258wvC2KhCsS1wCsc11h9Nelt-vrq1EaESyFjwYpTRlxgkR-x4xDBg5chxzcO2G_cNKn9l3qmYODgSTJZwJqqpjYKsodlklc9nVTIRIxnsHwPwgWTph8I_lkTS8v7ixTk0rsfYu55XGebrfNx4cve9a1uCj_8yT9vNmnSJlRTqSdrc9I7_3tRZisN_2Y3cJKJ8E5zWL2LuI4nNONqzOCKedRzrvNb_Oh3uROJgykRFOAvF5ljHPjqXCaNvkrNqBZP2jRG8RoF5OWwHPyimgkntZzBdY2F-ZluusLwl2kb2CPvCd9KruSor4kV_r2MSH7GP0SP_Pd0xTXpbjVsGXvFKE2gRyFog95z-8m500qQJxtZX3RDFjCnjuesDxfXSCeWWTrKFeF3QdUAm4ig2Q15ZP3tVc1vgzAemM7k1YkH8WaKE2oF1BpFj2HYtz7EREAkTj_TycJ8Erl10gsZlnM9rvTKPA9uA4of7lrN_V8gOYGydg2yYRpd4GkVeYLOw1DvHPg3npHmhzDnPegIw2skuB1P1yrxO7tDFxd4-uXnwLD4DnTDCyPHqF-aq8I6wpYGwY454HNnkJ7pzzpeCONSkFrIjqWd6l1XcMjCYYC_AAQIthqd9cTAQIqnBhewA7Q7XOYWkY

### update a product 
PATCH {{url_dev}}/products/669a22e2708fda5472ba0225
Content-Type: application/json
x-api-key: 021ee34a3780763e754c19b0dcfa721baec7b684848ad7a7db1cfdd37f92935599445c6c1c2f99f34cfa04fec4536d90c9534c4ac9d07856a8dc41b875a204c0
x-client-id: 6695321d5d8a7a6cddde90d4   
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njk1MzIxZDVkOGE3YTZjZGRkZTkwZDQiLCJlbWFpbCI6InNob3B0aXBqczIxMTU1MjI3QGdtYWlsLmNvbSIsImlhdCI6MTcyMTM3NzY5NywiZXhwIjoxNzIxNTUwNDk3fQ.BvjCByEeRQRpKakhIaK0of9Yv86f1l8uAZ3RvlEFdMhceezIEdzJmciGZJcsiEXbawqSz0SsaK2COqw3qpUKl4svRKUpIeZj_fQSbVlMf85Dpza7EiXVrJVXVhhL7z5HkiV-mcljGrpuq8xGBRQd6359Khwy-HGcOZyAYNfZRqAbHobinmfSaBLazd4hnpc8rTkxCc0Il63GJinBj3a8syQvsOm5rNvN5bg32WAFDcG2pe9pHKC4qh6vZHqlLVAQDQg1bIQvipk21_bbA4SMLLpWuddWORS5UD2yzQbhNPvpB3uIRmpNdz0ecWZbEBvwbqwVdOIFaMOJSD_T0mOi0Lm1CXtXe1yJJXA-6W3YiYjtB4GEFaDwXGqOdVIdwnGDOtVChgvU9T50ldUfOqgdXyCMvkhiWagsw9bq3CSAmMvCgwRBhWAW2YUDYJPIQ_qW-Ni-nlA-aXeZ2SyDf4bzR94wHcBiYogI3yGacBh9yNUrnpnS5XzM8gHND0GiYQZKaPg0NBULOWqfBtFSa5hDZSW6UV4mDngnny2ULK_gHwXelOhy6xmVxJ8qECrrtgHnz-g7vtQa8pD3Uvu9_tkerPfgAGBDUBDJ3cZrqRbBlBSuMautQxVU3SCtr_hXsoKT3nr4a3W1kW9xb3dkFRM_hAaAUyCxV0bIo1fSyi4MqhM


{
    "product_name": "table big",
    "product_quantity": null

}

